databases:
  - name: wealthgravity-db
    plan: free
    databaseName: wealthgravity
    user: wealthgravity

services:
  - type: web
    name: wealthgravity
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn wealthgravity.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wealthgravity-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: RENDER
        value: "true"
